### PR TITLE
[meta] Stop publishing development files

### PR DESCRIPTION
**Pull request by EvanHahn**
This package is currently being published with unnecessary files, such as `.eslintrc` and the `test/` directory.

This removes the following files:

- .eslintrc
- .github/FUNDING.yml
- .nycrc
- test/index.js

You can see the difference by comparing the results of `npm pack --dry-run`.

It does this by replacing `.npmignore`, a blocklist, with [the `files` property in package.json][0], an allowlist.

[0]: https://docs.npmjs.com/cli/v8/configuring-npm/package-json/#files

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
They are quite necessary; `npm explore foo && npm install && npm test` should always work.

Additionally, `files` is massively dangerous and should never be used; only `.npmignore` should be used.

**Comment by EvanHahn** [comment]
Sounds good. Thanks for taking a look!

Out of curiosity, what's the risk of `files`? Is the idea that you might forget to publish something, breaking things for people?

**Comment by EvanHahn** [comment]
Also: should `.github/FUNDING.yml` be included?

**Comment by ljharb** [comment]
Yes, precisely. The damage caused by breaking people is FAR, far more costly than the damage caused by accidentally publishing an extra file - even if it leaks a credential, that's a quick fix one person can do that only impacts me, compared to a fix that only I can do that impacts millions of people.

It's fair that i could npmignore the FUNDING.yml file, but that's a few bytes, so i typically include it so that funding information is present.

**Pull request closed without merging**
